fix breakage due to today's patch from youthcat
NullReferenceException: Object reference not set to an instance of an object
  at LSTMMod.LSTM+Patch.Mod_entitySignPool_Postfix (EntitySignRenderer __instance) [0x00007] in <b48996803f5644cbbb92da04353e603c>:0
  at EntitySignRenderer.Draw () [0x00099] in <c3b295ce06254256906510939c4119d1>:0
  at FactoryModel.OnCameraPostRender (UnityEngine.Camera cam) [0x000d9] in <c3b295ce06254256906510939c4119d1>:0
  at (wrapper delegate-invoke) System.Action`1[UnityEngine.Camera].invoke_void_T(UnityEngine.Camera)
  at MainCamera.OnPostRender () [0x00007] in <c3b295ce06254256906510939c4119d1>:0