fix npe due to today's youthcat patch
[Warning:  HarmonyX] AccessTools.Field: Could not find field for type UIStatisticsWindow and name entriesLen
System.ArgumentException: FieldRefAccess<UIStatisticsWindow, System.Int32> for Statistics Window (UIStatisticsWindow), entriesLen caused an exception ---> System.MissingFieldException: Field 'UIStatisticsWindow.entriesLen' not found.
  at HarmonyLib.AccessTools.GetInstanceField (System.Type type, System.String fieldName) [0x00010] in <7f26c0a74c5b43c2a5fc5efd29ec63d6>:0
  at HarmonyLib.AccessTools.FieldRefAccess[T,F] (T instance, System.String fieldName) [0x00032] in <7f26c0a74c5b43c2a5fc5efd29ec63d6>:0
   --- End of inner exception stack trace ---
  at HarmonyLib.AccessTools.FieldRefAccess[T,F] (T instance, System.String fieldName) [0x00092] in <7f26c0a74c5b43c2a5fc5efd29ec63d6>:0
  at LSTMMod.UIStatisticsWindowAgent.PostCreate () [0x00023] in <b48996803f5644cbbb92da04353e603c>:0
  at LSTMMod.LSTM+Patch.UIGame__OnCreate_Postfix () [0x0003f] in <b48996803f5644cbbb92da04353e603c>:0
  at UIGame._OnCreate () [0x003c9] in <c3b295ce06254256906510939c4119d1>:0
  at ManualBehaviour._Create () [0x00030] in <c3b295ce06254256906510939c4119d1>:0